### ISSUE TITLE
URL Change....

### ISSUE THREAD

**Issue by tjsoftworks** [buccolo/detroit-example#1]
In your blog post:

the line 
repository "https://github.com/brunobuccolo/detroit-example.git"
needs to be updated to the current url.

repository "https://github.com/buccolo/detroit-example.git"

or
git@github.com:buccolo/detroit-example.git

**Comment by buccolo** [comment]
Hey @tjsoftworks 

Awesome! Thanks for the heads up.

Just fixed it :beers:
